services:
  - type: web
    name: web-service-lab1
    env: python
    plan: free
    python:
      version: "3.11.8"
    buildCommand: pip install -r requirements.txt
    startCommand: cd flaskapp && gunicorn wsgi:app -b 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
